module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'chore',
        'ci',
        'cultural',
        'i18n',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'consultation',
        'hexagram',
        'ai',
        'auth',
        'ui',
        'api',
        'db',
        'cultural',
        'performance',
        'accessibility',
        'testing',
        'docs',
        'deps',
      ],
    ],
    'subject-case': [2, 'never', ['start-case', 'pascal-case', 'upper-case']],
    'subject-max-length': [2, 'always', 72],
    'body-max-line-length': [2, 'always', 100],
  },
};
